### ISSUE TITLE
add topic materials-science

### ISSUE THREAD

**Issue by Beliavsky** [wonnie87/NMCube#1]
I have added your repo to the category Materials Science in a [list of Fortran codes](https://github.com/Beliavsky/Fortran-code-on-GitHub) I maintain. I suggest adding the topic materials-science in the About section.

If I have misclassified the project please inform me.

**Comment by wonnie87** [comment]
Thank you for maintaining a directory of Fortran codes and adding our code to the list. 
The topic of this code lies across many fields, including Materials Science, but it would better fit the **Physics** category if I have to pick the most representative one.
I have added the topics in the About section as you suggested.
